apiVersion: v1
kind: Service
metadata:
  name: schoolspace-frontend
  namespace: school-space
spec:
  selector:
    app: schoolspace-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
