apiVersion: v1
kind: Service
metadata:
  name: schoolspace-backend
  namespace: school-space
spec:
  selector:
    app: schoolspace-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
