apiVersion: apps/v1
kind: Deployment
metadata:
  name: schoolspace-backend
  namespace: school-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schoolspace-backend
  template:
    metadata:
      labels:
        app: schoolspace-backend
    spec:
      containers:
        - name: backend
          image: <DOCKER_USERNAME>/schoolspaceservices:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://schoolspace-db.c6f8qe264enx.us-east-1.rds.amazonaws.com:3306/schoolspacedb?allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: Abc123...
