services:
  #mysql:
    #image: mysql:8
  #  environment:
  #    MYSQL_DATABASE: schoolspacedb
  #  ports:
 #     - "3307:3306"
  #  healthcheck:
  #    test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #    interval: 10s
   #   timeout: 5s
  #    retries: 5
  #  networks:
  #    - backend

  schoolspaceservices:
    build:
      context: ../school-space-services
      dockerfile: Dockerfile
    container_name: schoolSpaceServices
    image: schoolspaceservices
    ports:
      - "8080:8080"
   ## depends_on:
     # mysql:
     #   condition: service_healthy
    environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/schoolspacedb?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_URL: jdbc:mysql://schoolspace-db.c6f8qe264enx.us-east-1.rds.amazonaws.com:3306/schoolspace?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Abc123...
      DB_HOST: schoolspace-db.c6f8qe264enx.us-east-1.rds.amazonaws.com
      DB_USER: root
      DB_PASSWORD: Abc123...
    labels:
      ARTIFACT_CATEGORY: Computation
      Replicas: 1
    networks:
      - backend

  schoolspaceclient:
    build:
      context: ../school-space-client
      dockerfile: Dockerfile
    #  args:
    #    - REACT_APP_API_URL=http://schoolspaceservices:8080
    container_name: schoolSpaceClient
    ports:
      - "3000:80"
    depends_on:
      - schoolspaceservices
    environment:
      - REACT_APP_API_URL=http://schoolspaceservices:8080
    #  args:
    #  - VITE_API_URL=http://$(curl http://169.254.169.254/latest/meta-data/public-ipv4):8080
    networks:
      - backend

networks:
  backend:
